// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3XiMUEU-gHb7fAU_uclxtrXoiPGbe2F4',
    appId: '1:72859624343:web:a7cf8ab2daa77948f71ad2',
    messagingSenderId: '72859624343',
    projectId: 'gifts-app-f22ee',
    authDomain: 'gifts-app-f22ee.firebaseapp.com',
    storageBucket: 'gifts-app-f22ee.firebasestorage.app',
    measurementId: 'G-095XPH3RGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVKSLTnU6f0NFvpRwsedzJt_9tm5r3q_c',
    appId: '1:72859624343:android:034e59ba365ecd69f71ad2',
    messagingSenderId: '72859624343',
    projectId: 'gifts-app-f22ee',
    storageBucket: 'gifts-app-f22ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDujw8VK7erofeeIWmpfWl9dmra9z2iJG8',
    appId: '1:72859624343:ios:f7e18af206743541f71ad2',
    messagingSenderId: '72859624343',
    projectId: 'gifts-app-f22ee',
    storageBucket: 'gifts-app-f22ee.firebasestorage.app',
    iosBundleId: 'com.example.giftsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDujw8VK7erofeeIWmpfWl9dmra9z2iJG8',
    appId: '1:72859624343:ios:f7e18af206743541f71ad2',
    messagingSenderId: '72859624343',
    projectId: 'gifts-app-f22ee',
    storageBucket: 'gifts-app-f22ee.firebasestorage.app',
    iosBundleId: 'com.example.giftsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3XiMUEU-gHb7fAU_uclxtrXoiPGbe2F4',
    appId: '1:72859624343:web:3ffa7d19583df2f7f71ad2',
    messagingSenderId: '72859624343',
    projectId: 'gifts-app-f22ee',
    authDomain: 'gifts-app-f22ee.firebaseapp.com',
    storageBucket: 'gifts-app-f22ee.firebasestorage.app',
    measurementId: 'G-PNFW2653QE',
  );
}
